// i18n namespace 'notifyTemplates' — owner: services-notify (E): notification + email texts. Nested keys, Vietnamese text, {param} placeholders.
// Generated by the service layer (bell notifications, simulated emails, Zalo text). Neutral tone, client wording per SPEC §1.
const notifyTemplates = {
  common: {
    /** fallback pronoun when no salutation is stored */
    pronoun: 'anh/chị',
    genericAddress: 'anh/chị',
    newEra: 'New Era',
    impact: ' Nếu chưa làm: {impact}',
    /** impact texts that already start with this word are appended as-is (no "Nếu chưa làm:" prefix) */
    impactLead: 'nếu',
    impactPlain: ' {impact}',
  },
  due: {
    overdue: 'đã quá hạn {days} ngày',
    today: 'đến hạn hôm nay',
    left: 'còn {days} ngày',
  },
  email: {
    subject: '{title}',
    subjectUrgent: '[Gấp] {title}',
    greeting: 'Chào {name},',
    open: 'Mở trực tiếp: {url}',
    signoff: 'New Era · Client Hub',
  },
  task: {
    client_approved: {
      internal: {
        title: '{account} đã duyệt “{task}”',
        body: '{actor} đã duyệt việc “{task}” (hạn {due}).{note}',
        note: ' Ghi chú: “{note}”',
      },
    },
    client_changes_requested: {
      internal: {
        title: '{account} đề nghị chỉnh sửa “{task}”',
        body: '{actor} đề nghị chỉnh sửa việc “{task}”.{note} Việc đang chờ New Era xử lý.',
        note: ' Lý do: “{note}”',
      },
    },
    client_submitted: {
      internal: {
        title: '{account} đã gửi tài liệu: “{task}”',
        body: '{actor} đã gửi tài liệu cho việc “{task}”.{note} Việc đang chờ New Era kiểm tra.',
        note: ' Ghi chú: “{note}”',
      },
    },
    client_payment_reported: {
      internal: {
        title: '{account} báo đã chuyển khoản: “{task}”',
        body: '{actor} đã báo chuyển khoản kèm chứng từ cho việc “{task}”.{note} Việc đang chờ New Era đối soát.',
        note: ' Ghi chú: “{note}”',
      },
    },
    client_confirmed: {
      internal: {
        title: '{account} đã xác nhận “{task}”',
        body: '{actor} đã xác nhận việc “{task}”.{note}',
        note: ' Ghi chú: “{note}”',
      },
    },
    client_answered: {
      internal: {
        title: '{account} đã trả lời “{task}”',
        body: '{actor} đã trả lời việc “{task}”.{note}',
        note: ' Nội dung: “{note}”',
      },
    },
    client_question: {
      internal: {
        title: '{account} hỏi lại về “{task}”',
        body: '{actor} gửi câu hỏi về việc “{task}” (hạn {due}).{note}',
        note: ' Câu hỏi: “{note}”',
      },
    },
    comment_shared: {
      internal: {
        title: '{account}: bình luận mới ở “{task}”',
        body: '{actor} bình luận về việc “{task}”.{note}',
        note: ' Nội dung: “{note}”',
      },
      client: {
        title: 'New Era trả lời ở “{task}”',
        body: '{actor} (New Era) đã trả lời về việc “{task}”.{note}',
        note: ' Nội dung: “{note}”',
      },
    },
    returned_to_client: {
      client: {
        title: 'New Era đã cập nhật “{task}”',
        body: 'New Era đã gửi lại việc “{task}” để {pronoun} xem tiếp, hạn {due}.{note}',
        note: ' Lời nhắn: “{note}”',
      },
    },
    submission_accepted: {
      client: {
        title: 'New Era đã nhận “{task}”',
        body: 'New Era đã kiểm tra và hoàn tất việc “{task}”. Cảm ơn {pronoun}.{note}',
        note: ' Ghi chú: “{note}”',
      },
    },
    task_assigned_client: {
      client: {
        title: 'Việc mới cần {pronoun} xử lý: “{task}”',
        body: 'Việc “{task}” có hạn {due} ({relative}).{impact}{note}',
        note: ' Lời nhắn: “{note}”',
      },
    },
    delegated: {
      client: {
        title: '{actor} giao cho {pronoun} việc “{task}”',
        body: 'Việc “{task}” có hạn {due} ({relative}).{note}{impact}',
        note: ' Lời nhắn: “{note}”',
      },
    },
    unblocked: {
      internal: {
        title: 'Đã mở chặn: “{task}”',
        body: '{account}: việc “{task}” đã có thể bắt đầu, hạn {due}.{note}',
        note: ' Lý do: “{note}”',
      },
      client: {
        title: 'Việc “{task}” đã sẵn sàng',
        body: 'Việc “{task}” đã có thể xử lý, hạn {due} ({relative}).{impact}',
      },
    },
  },
  reminder: {
    manual: {
      title: 'New Era nhắc việc: “{task}”',
      body: 'New Era nhắc {pronoun} việc “{task}” (hạn {due}, {relative}).{impact} {Pronoun} xem và xử lý giúp.',
    },
    /** bulk "Nhắc khách (N)": one mail per person listing every task (each with its deep link) */
    manyMail: {
      subject: 'New Era nhắc {count} việc cần xử lý',
      intro: 'New Era nhắc {pronoun} {count} việc đang chờ phía {pronoun}:',
      item: '• “{task}” – hạn {due} ({relative})',
      outro: '{Pronoun} xem và xử lý giúp. Cảm ơn {pronoun}!',
      open: 'Xem tất cả việc: {url}',
    },
    auto: {
      title: '{relative}: “{task}”',
      body: 'Việc “{task}” có hạn {due} ({relativeLower}).{impact}',
    },
  },
  escalation: {
    client: {
      title: 'Mốc {milestones} đang chờ việc “{task}”',
      body: 'Việc “{task}” đã quá hạn {days} ngày (hạn {due}) và đang giữ mốc {milestones}, dự báo lùi {delay} ngày. {Pronoun} xem giúp để dự án tiếp tục theo kế hoạch.',
    },
    clientPlain: {
      title: 'Việc “{task}” đã quá hạn {days} ngày',
      body: 'Việc “{task}” đã quá hạn {days} ngày (hạn {due}) và đang ảnh hưởng tiến độ chung. {Pronoun} xem giúp để dự án tiếp tục theo kế hoạch.',
    },
    internal: {
      title: 'Leo thang: {account} – “{task}” quá hạn {days} ngày',
      body: '{account}: việc phía khách “{task}” ({assignee}) đã quá hạn {days} ngày, đang giữ mốc {milestones} (dự báo lùi {delay} ngày). Đã báo Người quyết định phía khách.',
    },
  },
  internalOverdue: {
    title: 'Việc quá hạn {days} ngày: “{task}”',
    body: '{account}: việc “{task}” có hạn {due}.{held}',
    held: ' Đang giữ mốc {milestones}.',
  },
  quote: {
    approval_requested: {
      title: 'Báo giá cần duyệt: {account} – {code} v{version}',
      body: '{actor} đề nghị duyệt báo giá “{quote}” cho {account}.{note}',
      note: ' Ghi chú: “{note}”',
    },
    approved: {
      title: 'Báo giá {code} v{version} đã được duyệt',
      body: '{actor} đã duyệt báo giá “{quote}” cho {account}. Có thể gửi khách.{note}',
      note: ' Ghi chú: “{note}”',
    },
    approval_rejected: {
      title: 'Báo giá {code} v{version} cần chỉnh lại',
      body: '{actor} chưa duyệt báo giá “{quote}” cho {account}.{note} Báo giá đã chuyển về nháp.',
      note: ' Lý do: “{note}”',
    },
    sent: {
      title: 'New Era gửi báo giá “{quote}”',
      body: 'Báo giá {code} v{version} có hiệu lực đến {valid}. {Pronoun} xem và chấp thuận hoặc đề nghị điều chỉnh ngay trong Client Hub.',
    },
    accepted: {
      title: '{account} đã chấp thuận báo giá {code} v{version}',
      body: '{actor} đã chấp thuận báo giá “{quote}”.{note}',
      note: ' Ghi chú: “{note}”',
    },
    changes_requested: {
      title: '{account} đề nghị điều chỉnh báo giá {code} v{version}',
      body: '{actor} đề nghị điều chỉnh báo giá “{quote}”.{note}',
      note: ' Nội dung: “{note}”',
    },
  },
  payment: {
    invoice_due: {
      internal: {
        title: '{account}: đợt “{name}” đến hạn xuất hóa đơn',
        body: 'Đợt “{name}” ({amount}) đã đến hạn xuất hóa đơn, hạn thanh toán {due}.',
      },
    },
    invoiced: {
      client: {
        title: 'Hóa đơn đợt “{name}”',
        body: 'New Era đã xuất hóa đơn{invoice} cho đợt “{name}”: {amount}, hạn thanh toán {due}.',
      },
      invoice: ' số {invoice}',
    },
    reported: {
      internal: {
        title: '{account} báo đã chuyển khoản đợt “{name}”',
        body: '{actor} đã báo chuyển khoản {amount} cho đợt “{name}”. Cần đối soát và xác nhận đã thu.',
      },
    },
    paid: {
      client: {
        title: 'New Era đã nhận thanh toán đợt “{name}”',
        body: 'New Era đã ghi nhận {amount} cho đợt “{name}”. Cảm ơn {pronoun}.',
      },
    },
    overdue: {
      internal: {
        title: '{account}: đợt “{name}” quá hạn {days} ngày',
        body: 'Đợt “{name}” ({amount}) có hạn thanh toán {due}, đã quá hạn {days} ngày.',
      },
      client: {
        title: 'Đợt thanh toán “{name}” đã quá hạn {days} ngày',
        body: 'Đợt “{name}” ({amount}) có hạn thanh toán {due}. {Pronoun} kiểm tra giúp; nếu đã chuyển khoản, {pronoun} có thể báo ngay trong Client Hub.',
      },
    },
  },
  summary: {
    subject: 'Tóm tắt {count} cập nhật mới',
    intro: 'Để {pronoun} không nhận quá nhiều email, các cập nhật dưới đây được gom lại:',
    item: '• {subject}',
    /** deep link under each line */
    itemLink: '  Mở: {url}',
    /** a reminder re-dated on the day the summary is sent */
    reminderLine: '{relative}: “{task}”',
    open: 'Xem tất cả: {url}',
  },
  digest: {
    subject: 'Bản tin tuần {week} – Client Hub',
    notifTitle: 'Bản tin tuần {week} đã sẵn sàng',
    notifBody: 'Tình hình, việc đã xong, việc đang chờ {pronoun} và mốc sắp tới của {count} khách hàng.',
    notifBodyClient: 'Tình hình dự án, việc đã xong, việc đang chờ {pronoun} và mốc sắp tới.',
    intro: 'Bản tin tuần bắt đầu {week}.',
    section: '■ {account} · {health}',
    done: 'Đã xong 7 ngày qua: {count} việc',
    waitingClient: 'Việc cần {pronoun} xử lý: {count}',
    waitingInternal: 'Việc đang chờ New Era: {count}',
    item: '  • {title} – hạn {due} ({relative})',
    more: '  • … và {count} việc khác',
    milestones: 'Mốc sắp tới:',
    milestone: '  • {name}: kế hoạch {planned} → dự báo {forecast}',
    milestoneOnPlan: '  • {name}: {planned}',
    noMilestone: 'Không có mốc nào trong 3 tuần tới.',
    empty: 'Tuần này chưa có khách hàng nào để tổng hợp.',
    open: 'Xem bản tin đầy đủ: {url}',
    status: {
      on_track: 'Dự án đang chạy đúng kế hoạch.',
      due_soon_blocking: 'Có {count} việc sắp đến hạn có thể làm lùi mốc {milestone}.',
      overdue: 'Có {count} việc đã quá hạn.',
      payment_overdue: 'Có {count} đợt thanh toán đã quá hạn.',
      waiting_client: {
        client: 'Mốc {milestone} đang chờ {count} việc từ phía {pronoun}. Mỗi ngày chậm, {milestone} lùi thêm 1 ngày.',
        /** the waited-for task is a colleague's */
        person: 'Mốc {milestone} đang chờ {count} việc từ {name} ({company}). Mỗi ngày chậm, {milestone} lùi thêm 1 ngày.',
        company: 'Mốc {milestone} đang chờ {count} việc từ phía {company}. Mỗi ngày chậm, {milestone} lùi thêm 1 ngày.',
        internal: 'Mốc {milestone} đang chờ {count} việc từ phía khách, dự báo lùi {delay} ngày.',
      },
      waiting_internal: 'Mốc {milestone} đang lùi {delay} ngày do New Era chậm việc “{task}”. New Era đang xử lý.',
      waiting_internal_hidden: 'Mốc {milestone} đang lùi {delay} ngày do New Era chậm một việc chuẩn bị. New Era đang xử lý.',
      generic: {
        blocked: 'Dự án đang có việc quá hạn giữ mốc, cần xử lý sớm.',
        attention: 'Có một số điểm cần chú ý trong tuần này.',
        on_track: 'Dự án đang chạy đúng kế hoạch.',
      },
    },
  },
  zalo: {
    text: 'Chào {address}, New Era xin nhắc {pronoun} việc “{task}” (hạn {due}, {relative}). {Pronoun} xem và xử lý giúp tại: {url}. Cảm ơn {pronoun}!',
  },
};

export default notifyTemplates;
