// Tiny one-page PDF writer for the demo documents. The text keeps its Vietnamese diacritics: each document embeds a
// TrueType subset of DejaVu Sans (./pdfFont, generated by vendor/fonts/build-pdf-font.ps1) as a CID font
// (Identity-H, ToUnicode for copy / search). Bold is the same font filled and stroked. A character the font lacks
// is folded to ASCII (toAscii). The output is a byte string (every char < 256), so byte offsets equal string indices.

import { PDF_FONT } from './pdfFont';

export interface PdfSection {
  heading?: string;
  /** lines starting with '- ' are rendered as indented bullets */
  lines: string[];
}

export interface PdfDoc {
  title: string;
  subtitle?: string;
  /** label/value rows under the title */
  meta?: [string, string][];
  sections: PdfSection[];
  footer?: string;
}

const REPLACEMENTS: [RegExp, string][] = [
  [/đ/g, 'd'],
  [/Đ/g, 'D'],
  [/[–—]/g, '-'],
  [/[“”]/g, '"'],
  [/[‘’]/g, "'"],
  [/₫/g, 'VND'],
  [/…/g, '...'],
  [/•/g, '-'],
  [/→/g, '->'],
  [/×/g, 'x'],
  [/\s?°C/g, ' do C'],
  [/°/g, ' do'],
  [/≤/g, '<='],
  [/≥/g, '>='],
];

/** 'Đặt hàng – 1.250.000 ₫' → 'Dat hang - 1.250.000 VND' (fallback for a character the embedded font lacks) */
export function toAscii(s: string): string {
  let out = s;
  for (const [re, rep] of REPLACEMENTS) out = out.replace(re, rep);
  return out
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .replace(/[^\x20-\x7e]/g, '?');
}

// ───────────────────────────── font data ─────────────────────────────

interface FontData {
  glyphs: Uint8Array;
  glyphOf: Map<number, number>;
}

let fontCache: FontData | null = null;

function decodeBase64(b64: string): Uint8Array {
  const raw = atob(b64);
  const out = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i++) out[i] = raw.charCodeAt(i);
  return out;
}

function fontData(): FontData {
  if (fontCache) return fontCache;
  const glyphOf = new Map<number, number>();
  PDF_FONT.codePoints.forEach((cp, i) => glyphOf.set(cp, PDF_FONT.charGlyphs[i] ?? 0));
  fontCache = { glyphs: decodeBase64(PDF_FONT.glyphs), glyphOf };
  return fontCache;
}

const QUESTION = 63;

/** glyph numbers (PDF_FONT numbering) of a string; `used` records the character each glyph stands for */
function glyphsOf(s: string, used?: Map<number, string>): number[] {
  const { glyphOf } = fontData();
  const out: number[] = [];
  const push = (ch: string): boolean => {
    const g = glyphOf.get(ch.codePointAt(0) ?? QUESTION);
    if (g === undefined) return false;
    out.push(g);
    if (used && !used.has(g)) used.set(g, ch);
    return true;
  };
  for (const ch of s.normalize('NFC')) {
    if (push(ch)) continue;
    for (const a of toAscii(ch)) if (!push(a)) push('?');
  }
  return out;
}

function advance(g: number): number {
  return PDF_FONT.advances[g] ?? 0;
}

function measure(s: string, size: number): number {
  return (glyphsOf(s).reduce((sum, g) => sum + advance(g), 0) * size) / PDF_FONT.unitsPerEm;
}

function wrap(text: string, size: number, maxWidth: number): string[] {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let cur = '';
  for (const w of words) {
    const next = cur ? `${cur} ${w}` : w;
    if (cur && measure(next, size) > maxWidth) {
      lines.push(cur);
      cur = w;
    } else {
      cur = next;
    }
  }
  if (cur) lines.push(cur);
  return lines.length ? lines : [''];
}

// ───────────────────────────── TrueType subset ─────────────────────────────

function glyphSlice(g: number): Uint8Array {
  const offsets = PDF_FONT.glyphOffsets;
  return fontData().glyphs.subarray(offsets[g] ?? 0, offsets[g + 1] ?? 0);
}

/** component records of a composite glyph: [byte offset of the glyph index, glyph number] */
function componentsOf(bytes: Uint8Array): [number, number][] {
  const out: [number, number][] = [];
  if (bytes.length < 10 || ((bytes[0] ?? 0) & 0x80) === 0) return out; // numberOfContours ≥ 0: simple glyph
  let p = 10;
  for (;;) {
    const flags = ((bytes[p] ?? 0) << 8) | (bytes[p + 1] ?? 0);
    out.push([p + 2, ((bytes[p + 2] ?? 0) << 8) | (bytes[p + 3] ?? 0)]);
    p += 4 + (flags & 1 ? 4 : 2);
    if (flags & 8) p += 2;
    else if (flags & 0x40) p += 4;
    else if (flags & 0x80) p += 8;
    if (!(flags & 0x20) || p >= bytes.length) break;
  }
  return out;
}

class Bytes {
  private parts: number[] = [];
  get length(): number {
    return this.parts.length;
  }
  u8(v: number): void {
    this.parts.push(v & 0xff);
  }
  u16(v: number): void {
    this.u8(v >> 8);
    this.u8(v);
  }
  u32(v: number): void {
    this.u16(v >>> 16);
    this.u16(v & 0xffff);
  }
  bytes(b: Uint8Array): void {
    for (const x of b) this.parts.push(x);
  }
  pad4(): void {
    while (this.parts.length % 4) this.parts.push(0);
  }
  toArray(): Uint8Array {
    return Uint8Array.from(this.parts);
  }
}

function checksum(b: Uint8Array, start = 0, end = b.length): number {
  let sum = 0;
  for (let i = start; i < end; i += 4) {
    const word = (((b[i] ?? 0) << 24) | ((b[i + 1] ?? 0) << 16) | ((b[i + 2] ?? 0) << 8) | (b[i + 3] ?? 0)) >>> 0;
    sum = (sum + word) >>> 0;
  }
  return sum;
}

interface Subset {
  /** the font program (glyf, head, hhea, hmtx, loca, maxp — what a PDF CID font needs) */
  ttf: Uint8Array;
  /** PDF_FONT glyph number → glyph number (= CID) in the subset */
  cidOf: Map<number, number>;
  /** PDF_FONT glyph numbers in subset order */
  order: number[];
}

function subsetFont(used: Iterable<number>): Subset {
  const want = new Set<number>([0, ...used]);
  const queue = [...want];
  for (let i = 0; i < queue.length; i++) {
    for (const [, c] of componentsOf(glyphSlice(queue[i] ?? 0))) {
      if (!want.has(c)) {
        want.add(c);
        queue.push(c);
      }
    }
  }
  const order = [...want].sort((a, b) => a - b);
  const cidOf = new Map(order.map((g, i): [number, number] => [g, i]));
  const n = order.length;

  const glyf = new Bytes();
  const loca = new Bytes();
  const hmtx = new Bytes();
  for (const g of order) {
    loca.u32(glyf.length);
    const src = glyphSlice(g);
    const copy = Uint8Array.from(src);
    for (const [at, c] of componentsOf(src)) {
      const to = cidOf.get(c) ?? 0;
      copy[at] = to >> 8;
      copy[at + 1] = to & 0xff;
    }
    glyf.bytes(copy);
    glyf.pad4();
    hmtx.u16(advance(g));
    hmtx.u16((PDF_FONT.lsbs[g] ?? 0) & 0xffff);
  }
  loca.u32(glyf.length);

  const head = decodeBase64(PDF_FONT.head);
  head.set([0, 0, 0, 0], 8); // checkSumAdjustment, set below
  head.set([0, 1], 50); // indexToLocFormat: long offsets
  const hhea = decodeBase64(PDF_FONT.hhea);
  hhea.set([n >> 8, n & 0xff], 34); // numberOfHMetrics
  const maxp = decodeBase64(PDF_FONT.maxp);
  maxp.set([n >> 8, n & 0xff], 4); // numGlyphs

  const tables: [string, Uint8Array][] = [
    ['glyf', glyf.toArray()],
    ['head', head],
    ['hhea', hhea],
    ['hmtx', hmtx.toArray()],
    ['loca', loca.toArray()],
    ['maxp', maxp],
  ];
  const out = new Bytes();
  out.u32(0x00010000);
  out.u16(tables.length);
  out.u16(64); // searchRange = 16 × 4 (largest power of two ≤ 6)
  out.u16(2); // entrySelector
  out.u16(tables.length * 16 - 64); // rangeShift
  let offset = 12 + tables.length * 16;
  const placed: number[] = [];
  for (const [tag, data] of tables) {
    const padded = new Uint8Array(Math.ceil(data.length / 4) * 4);
    padded.set(data);
    for (const ch of tag) out.u8(ch.charCodeAt(0));
    out.u32(checksum(padded));
    out.u32(offset);
    out.u32(data.length);
    placed.push(offset);
    offset += padded.length;
  }
  for (const [, data] of tables) {
    out.bytes(data);
    out.pad4();
  }
  const ttf = out.toArray();
  const headAt = placed[1] ?? 0;
  const adjust = (0xb1b0afba - checksum(ttf)) >>> 0;
  ttf.set([adjust >>> 24, (adjust >>> 16) & 0xff, (adjust >>> 8) & 0xff, adjust & 0xff], headAt + 8);
  return { ttf, cidOf, order };
}

// ───────────────────────────── page layout ─────────────────────────────

type Color = 'primary' | 'fg' | 'muted' | 'caption' | 'white';

const RGB: Record<Color | 'border', string> = {
  primary: '0.114 0.306 0.847',
  fg: '0.059 0.090 0.165',
  muted: '0.278 0.333 0.412',
  caption: '0.369 0.431 0.518',
  border: '0.898 0.914 0.941',
  white: '1 1 1',
};

interface TextRun {
  glyphs: number[];
  size: number;
  x: number;
  y: number;
  color: Color;
  bold: boolean;
}

type Op = string | TextRun;

const PAGE_W = 595;
const LEFT = 40;
const RIGHT = 555;
const BULLET_X = 58;

function layout(doc: PdfDoc, used: Map<number, string>): Op[] {
  const ops: Op[] = [];
  const run = (s: string, size: number, x: number, y: number, color: Color, bold = false): void => {
    ops.push({ glyphs: glyphsOf(s, used), size, x, y, color, bold });
  };

  ops.push(`${RGB.primary} rg 0 787 ${PAGE_W} 55 re f`);
  run('NEW ERA', 16, LEFT, 808, 'white', true);
  const brand = 'Client Hub · tài liệu mẫu';
  run(brand, 9, RIGHT - measure(brand, 9), 810, 'white');

  let y = 770;
  for (const line of wrap(doc.title, 18, RIGHT - LEFT)) {
    y -= 22;
    run(line, 18, LEFT, y, 'fg', true);
  }
  if (doc.subtitle) {
    y -= 4;
    for (const line of wrap(doc.subtitle, 11, RIGHT - LEFT)) {
      y -= 16;
      run(line, 11, LEFT, y, 'muted');
    }
  }
  y -= 14;
  for (const [label, value] of doc.meta ?? []) {
    wrap(value, 10, RIGHT - 170).forEach((part, i) => {
      y -= 15;
      if (i === 0) run(label, 10, LEFT, y, 'caption');
      run(part, 10, 170, y, 'fg');
    });
  }
  y -= 12;
  ops.push(`${RGB.border} RG 0.8 w ${LEFT} ${y} m ${RIGHT} ${y} l S`);
  for (const section of doc.sections) {
    if (y < 90) break;
    if (section.heading) {
      y -= 26;
      run(section.heading, 12, LEFT, y, 'primary', true);
      y -= 4;
    }
    for (const line of section.lines) {
      const bullet = line.startsWith('- ');
      const parts = wrap(bullet ? line.slice(2) : line, 10.5, RIGHT - (bullet ? BULLET_X : LEFT));
      parts.forEach((part, i) => {
        y -= 15;
        if (y < 70) return;
        if (bullet && i === 0) run('•', 10.5, 46, y, 'fg');
        run(part, 10.5, bullet ? BULLET_X : LEFT, y, 'fg');
      });
    }
  }
  ops.push(`${RGB.border} RG 0.8 w ${LEFT} 58 m ${RIGHT} 58 l S`);
  run(doc.footer ?? 'New Era – Công ty giải pháp chuyển đổi số', 8, LEFT, 44, 'caption');
  run('Tài liệu mẫu trong bản demo Client Hub, không có giá trị pháp lý.', 8, LEFT, 32, 'caption');
  return ops;
}

function hex4(n: number): string {
  return n.toString(16).toUpperCase().padStart(4, '0');
}

function contentStream(ops: Op[], cidOf: Map<number, number>): string {
  return ops
    .map((op) => {
      if (typeof op === 'string') return op;
      const color = RGB[op.color];
      const hex = op.glyphs.map((g) => hex4(cidOf.get(g) ?? 0)).join('');
      // bold = the same outlines filled AND stroked (render mode 2) with a hairline proportional to the size
      const mode = op.bold ? `2 Tr ${(op.size * 0.035).toFixed(2)} w ${color} RG` : '0 Tr';
      return `${color} rg ${mode} BT /F1 ${op.size} Tf ${op.x.toFixed(2)} ${op.y} Td <${hex}> Tj ET`;
    })
    .join('\n');
}

function toUnicodeCMap(order: number[], used: Map<number, string>): string {
  const entries: string[] = [];
  order.forEach((g, cid) => {
    const ch = used.get(g);
    if (!ch) return;
    const units = Array.from({ length: ch.length }, (_, i) => hex4(ch.charCodeAt(i))).join('');
    entries.push(`<${hex4(cid)}> <${units}>`);
  });
  const blocks: string[] = [];
  for (let i = 0; i < entries.length; i += 100) {
    const chunk = entries.slice(i, i + 100);
    blocks.push(`${chunk.length} beginbfchar\n${chunk.join('\n')}\nendbfchar`);
  }
  return [
    '/CIDInit /ProcSet findresource begin',
    '12 dict begin',
    'begincmap',
    '/CIDSystemInfo << /Registry (Adobe) /Ordering (UCS) /Supplement 0 >> def',
    '/CMapName /Adobe-Identity-UCS def',
    '/CMapType 2 def',
    '1 begincodespacerange',
    '<0000> <FFFF>',
    'endcodespacerange',
    ...blocks,
    'endcmap',
    'CMapName currentdict /CMap defineresource pop',
    'end',
    'end',
  ].join('\n');
}

/** 'ABCDEF': the subset tag PDF requires before a subset font's name, derived from its glyphs (stable output) */
function subsetTag(order: number[]): string {
  let h = 2166136261;
  for (const g of order) h = Math.imul(h ^ g, 16777619) >>> 0;
  let tag = '';
  for (let i = 0; i < 6; i++) {
    tag += String.fromCharCode(65 + (h % 26));
    h = Math.floor(h / 26) + i * 7919;
  }
  return tag;
}

/** PDF text string in UTF-16BE (document title with diacritics) */
function pdfTextString(s: string): string {
  let hex = 'FEFF';
  for (let i = 0; i < s.length; i++) hex += hex4(s.charCodeAt(i));
  return `<${hex}>`;
}

function binaryString(b: Uint8Array): string {
  let out = '';
  for (let i = 0; i < b.length; i += 8192) out += String.fromCharCode(...b.subarray(i, i + 8192));
  return out;
}

/** Raw PDF bytes as a byte string (use btoa for a data: URL). */
export function buildPdf(doc: PdfDoc): string {
  const used = new Map<number, string>();
  const ops = layout(doc, used);
  const { ttf, cidOf, order } = subsetFont(used.keys());
  const stream = contentStream(ops, cidOf);
  const upm = PDF_FONT.unitsPerEm;
  const k = (v: number): number => Math.round((v * 1000) / upm);
  const name = `${subsetTag(order)}+ClientHubSans`;
  const widths = order.map((g) => k(advance(g))).join(' ');
  const [x0, y0, x1, y1] = PDF_FONT.bbox;
  const capHeight = PDF_FONT.capHeight || Math.round(upm * 0.729);
  const cmap = toUnicodeCMap(order, used);
  const font = binaryString(ttf);

  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_W} 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 9 0 R >>`,
    `<< /Type /Font /Subtype /Type0 /BaseFont /${name} /Encoding /Identity-H /DescendantFonts [5 0 R] /ToUnicode 6 0 R >>`,
    `<< /Type /Font /Subtype /CIDFontType2 /BaseFont /${name} /CIDSystemInfo << /Registry (Adobe) /Ordering (Identity) /Supplement 0 >> /FontDescriptor 7 0 R /W [0 [${widths}]] /CIDToGIDMap /Identity >>`,
    `<< /Length ${cmap.length} >>\nstream\n${cmap}\nendstream`,
    `<< /Type /FontDescriptor /FontName /${name} /Flags 32 /FontBBox [${k(x0 ?? 0)} ${k(y0 ?? 0)} ${k(x1 ?? 0)} ${k(y1 ?? 0)}] /ItalicAngle 0 /Ascent ${k(PDF_FONT.ascent)} /Descent ${k(PDF_FONT.descent)} /CapHeight ${k(capHeight)} /StemV 80 /FontFile2 8 0 R >>`,
    `<< /Length ${font.length} /Length1 ${font.length} >>\nstream\n${font}\nendstream`,
    `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    `<< /Title ${pdfTextString(doc.title)} /Producer (Client Hub demo) >>`,
  ];
  let out = '%PDF-1.4\n%\xE2\xE3\xCF\xD3\n';
  const offsets: number[] = [];
  objects.forEach((body, i) => {
    offsets.push(out.length);
    out += `${i + 1} 0 obj\n${body}\nendobj\n`;
  });
  const xref = out.length;
  out += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const off of offsets) out += `${String(off).padStart(10, '0')} 00000 n \n`;
  out += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R /Info 10 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return out;
}
